version: "3.9"
services:
  opentelemetry-collector-contrib:
    image: "otel/opentelemetry-collector-contrib:0.71.0"
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ${CONFIG}:/etc/otel-collector-config.yml
    ports:
      - "52199:4317"


